// Copyright © 2026 Cyberus Technology GmbH
//
// SPDX-License-Identifier: Apache-2.0
//

use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::io::{Read, Write};
use std::path::Path;
use std::{env, fs};

use anyhow::Context;
use flate2::Compression;
use flate2::write::ZlibEncoder;
use quote::{format_ident, quote};

/// This is where the CPU profile generation tool writes the JSON files associated with
/// a CPU profile.
const X86_64_CPU_PROFILES_PATH: &str = "./src/x86_64/cpu_profiles";

fn main() -> anyhow::Result<()> {
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH")
        .context("Could not get env var CARGO_CFG_TARGET_ARCH")?;

    if target_arch == "x86_64" {
        generate_code_for_x86_64_cpu_profiles().context("CPU profile code generation failed")?;
        // We only want the build script to be rerun if new CPU profiles are generated, or the
        // build script itself changes (see the final println! before this function returns).
        println!("cargo::rerun-if-changed={X86_64_CPU_PROFILES_PATH}");
    }

    // Disable automatic rerun after package changes.
    // See: https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed
    println!("cargo::rerun-if-changed=build.rs");
    Ok(())
}

/// This function generates the `generated_cpu_profiles.rs` file which consists of the following:
///
/// - a `CpuProfile` enum with a `Host` variant and one additional variant per pre-generated CPU profile.
/// - A function `compressed_cpuid_data` that takes a `&CpuProfile` and returns the compressed CPUID adjustment data required for the given CPU profile.
/// - A function `compressed_msr_data` that takes a `&CpuProfile` and returns the compressed MSR adjustment data required for the given CPU profile.
///
/// This function works by traversing the JSON files in `X86_64_CPU_PROFILES_PATH` generated by
/// the CPU profile generation tool.
fn generate_code_for_x86_64_cpu_profiles() -> anyhow::Result<()> {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let profile_names = x86_64_cpu_profile_names()
        .context("Failed to extract CPU profile names from pre-generated JSON files")?;
    // Compress each CPUID and MSR JSON file
    compress_json_files(&profile_names, &out_dir)
        .context("Failed to create compressed CPU profile data files")?;

    let mut out = generate_cpu_profile_enum(&profile_names);
    out.push('\n');
    out.push_str(&generate_compressed_data_fn(
        &profile_names,
        DataType::Cpuid,
    ));
    out.push('\n');
    out.push_str(&generate_compressed_data_fn(&profile_names, DataType::Msr));

    let generated_file_path = Path::new(&out_dir).join("generated_cpu_profiles.rs");
    let mut f = fs::File::create(&generated_file_path)
        .with_context(|| format!("Could not create file with path:={generated_file_path:#?}"))?;
    f.write_all(out.as_bytes())
        .with_context(|| format!("Could not write to file with path:={generated_file_path:#?}"))?;
    Ok(())
}

/// The name of a pre-generated CPU profile.
///
/// Each CPU profile has two associated JSON files:
///
/// 1. <chosen-name-in-kebab-case>.cpuid.json
/// 2. <chosen-name-in-kebab-case>.msr.json
///
/// and each instance of `ProfileName` is extracted from
/// `<chosen-name-in-kebab-case>`.
struct ProfileName {
    /// The `kebab_case` name converted to camel case.
    camel_case: String,
    kebab_case: String,
}

/// Each CPU profile has two associated JSON files:
///
/// one for CPUID adjustment data and one for MSR adjustment data.
#[derive(Copy, Clone)]
enum DataType {
    Cpuid,
    Msr,
}

impl DataType {
    fn as_str(&self) -> &str {
        match self {
            Self::Cpuid => "cpuid",
            Self::Msr => "msr",
        }
    }
}

/// Traverse the `X86_64_CPU_PROFILES_PATH` and extract a `[ProfileName]` per encountered
/// pre-generated CPU profile.
fn x86_64_cpu_profile_names() -> anyhow::Result<Vec<ProfileName>> {
    let dir = fs::read_dir(X86_64_CPU_PROFILES_PATH)
        .with_context(|| format!("Could not read directory:={X86_64_CPU_PROFILES_PATH}"))?;

    let mut profile_names_kebab_case = BTreeSet::new();
    for entry in dir {
        let file = entry.with_context(|| {
            format!("Encountered error while traversing directory:={X86_64_CPU_PROFILES_PATH}")
        })?;
        let file_name = file.file_name().into_string().unwrap();
        let profile_name_kebab_case = {
            let dot_pos = file_name
                .find('.')
                .expect("all files in the cpu_profiles directory should contain a '.' character");
            file_name[..dot_pos].to_string()
        };
        profile_names_kebab_case.insert(profile_name_kebab_case);
    }

    let profile_name_iter = profile_names_kebab_case.into_iter().map(|kebab_case| {
        let mut camel_case = String::new();
        for part in kebab_case.split('-') {
            if let Some(first_char) = part.chars().next() {
                camel_case.extend(first_char.to_uppercase());
                let rest = &part[first_char.len_utf8()..];
                camel_case.push_str(rest);
            }
        }
        ProfileName {
            camel_case,
            kebab_case,
        }
    });
    Ok(profile_name_iter.collect())
}

/// Compresses the CPUID and MSR related JSON files per CPU profile
/// that are found in `X86_64_CPU_PROFILES_PATH`.
fn compress_json_files(names: &[ProfileName], out_dir: &OsStr) -> anyhow::Result<()> {
    for ProfileName {
        kebab_case,
        camel_case: _,
    } in names
    {
        let file_bytes = |data_type: &str| -> anyhow::Result<Vec<u8>> {
            let path =
                Path::new(X86_64_CPU_PROFILES_PATH).join(format!("{kebab_case}.{data_type}.json"));
            let mut file = fs::File::open(&path)
                .with_context(|| format!("Could not open file with path:={path:#?}"))?;
            let mut v = Vec::new();
            file.read_to_end(&mut v)
                .with_context(|| format!("Could not read contents of file with path:={path:#?}"))?;
            Ok(v)
        };
        let cpuid_bytes = file_bytes("cpuid")?;
        let msr_bytes = file_bytes("msr")?;
        let compress_to_file = |data_type: &str, data: &[u8]| -> anyhow::Result<()> {
            let path = Path::new(&out_dir).join(format!("{kebab_case}.{data_type}.zz"));
            let file = fs::File::create(&path)
                .with_context(|| format!("Could not create file with path:={path:#?}"))?;
            let mut encoder = ZlibEncoder::new(file, Compression::best());
            encoder.write_all(data).with_context(|| {
                format!("Could not write compressed bytes to file with path:={path:#?}")
            })?;
            encoder
                .flush()
                .with_context(|| format!("Could not flush to file with path:={path:#?}"))?;
            Ok(())
        };
        compress_to_file(DataType::Cpuid.as_str(), &cpuid_bytes)?;
        compress_to_file(DataType::Msr.as_str(), &msr_bytes)?;
    }

    Ok(())
}

/// Generates Rust code as a String defining a `CpuProfile` enum with a `Host` variant
/// together with a variant per entry in `profile_names`.
fn generate_cpu_profile_enum(profile_names: &[ProfileName]) -> String {
    // Obtain a vector of the non-host CPU profile enum variants from the previously parsed camel case names
    let non_host_enum_variants = non_host_cpu_profile_variants(profile_names);

    // Use the quote crate to build the CpuProfile enum as a TokenStream.
    let tokens = quote! {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
        #[serde(rename_all = "kebab-case")]
        pub enum CpuProfile {
            #[default]
            Host,
            #(#non_host_enum_variants),*
        }
    };

    // Parse this to a syntax tree and return it and convert it to a pretty printed string of Rust code
    let syntax_tree = syn::parse2(tokens).unwrap();
    prettyplease::unparse(&syntax_tree)
}

/// Generates the function that extracts the compressed bytes for `data_type` corresponding to the user's
/// selected CPU profile.
fn generate_compressed_data_fn(profile_names: &[ProfileName], data_type: DataType) -> String {
    let data_type_str = data_type.as_str();
    let doc_str = format!(
        "Extract compressed {data_type_str} CPU profile data corresponding to the given profile"
    );
    let non_host_enum_variants = non_host_cpu_profile_variants(profile_names);
    let compressed_file_names: Vec<String> = profile_names
        .iter()
        .map(
            |ProfileName {
                 kebab_case,
                 camel_case: _,
             }| format!("/{kebab_case}.{data_type_str}.zz"),
        )
        .collect();

    // Workaround to interpolate `data_type_str` in the function name within a `quote!` invocation.
    let fn_name_ident = format_ident!("compressed_{data_type_str}_data");

    // We now use quote! to produce our function that matches against each enum variant and returns the compressed file as a byte slice.
    //
    // Note that the compressed bytes are no longer stand alone files after compiling since we will use `include_bytes!` to compile them
    // into the final binary.
    let tokens = quote! {
        #[doc=#doc_str]
        fn #fn_name_ident (profile: &CpuProfile) -> Option<&'static [u8]> {
            use CpuProfile::*;
            match profile {
                Host => None,
                #(#non_host_enum_variants => Some(&include_bytes!(concat!(env!("OUT_DIR"), #compressed_file_names))[..])),*
            }
        }
    };

    // Parse this to a syntax tree and return it and convert it to a pretty printed string of Rust code
    let syntax_tree = syn::parse2(tokens).unwrap();
    prettyplease::unparse(&syntax_tree)
}

/// Converts the parsed CPU profile names to a enum variants that may be placed into a token stream.
fn non_host_cpu_profile_variants(names: &[ProfileName]) -> Vec<syn::Variant> {
    names
        .iter()
        .map(|name| {
            syn::parse_str(name.camel_case.as_str())
                .expect("Should be able to parse camelcase name to syn::Variant")
        })
        .collect()
}
